version: '3.8'
services:
  app:
    build:  .
    volumes:
      - .:/django
    ports:
      - 7000:7000
    image: app:django
    container_name: userInfo_contianer
    command:  python manage.py runserver 0.0.0.0:7000